import type { Metadata } from "next";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation/AppNavigation";

export const metadata: Metadata = {
  title: "Public App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navigation />
      {children}
      <Footer />
    </>
  );
}
